# .travis.yml

language: php

php:
  - 7.2

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --no-interaction -vvv
  - php artisan cache:clear
  - php artisan route:clear

before_install:
  - mysql -e 'CREATE DATABASE blog_test;'
  - before_script: echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - vendor/bin/phpunit

services:
  - mysql

notifications:
  email: false